#!/usr/bin/awk

BEGIN {
	print "/*! \\file"
	print " * AUTOGENERATED FILE, DO NOT EDIT, see src/debugflags.def instead."
	print " * Enumerate debug flags and their short description"
	print " */"
	print ""
}

/^\/\/\/ / {
	comment=substr($0, 5)
}

/^unsigned / {
	print "cout << \"\\t" $2 "\\t:\\t" comment "\\n\";"
}
