#!/bin/sh

git help clone | grep -q -- --shallow-submodules && shallow='--shallow-submodules' || shallow=

git clone --branch cuda-11.6 --depth 1 --recursive $shallow https://github.com/NVIDIA/thrust/
