#!/usr/bin/awk

BEGIN {
	print "/*! \\file"
	print " * AUTOGENERATED FILE, DO NOT EDIT, see src/debugflags.def instead."
	print " * A cascade of ifs to parse the debug flags passed on the command line."
	print " */"
	print ""
}

/^unsigned / {
	flag = $2;
	alt = gensub(/_/, "-", "g", flag);
	cond = "flag == \"" flag "\"";
	if ($alt != flag)
		cond = "(" cond ") || (flag == \"" alt "\")";
	print "if (" cond ") ret." flag " = 1; else "
}
