#!/bin/sh

abort() {
	echo "$1" 1>&2
	exit 1;
}

dir="$1"
shift
id="${1:-0}"

test -z "$dir" && abort "Please specify a dir"

files=
# Support specifying just the toplevel directory
if test -d "$dir" ; then
	test -d "$dir/data" && dir="$dir/data"
	test -d "$dir/testpoints" && dir="$dir/testpoints"
	files="$(find "$dir" -name 'testpoints_*.csv' | sort)"
	#DEBUG# printf ".%s." "$files"
	[ -z "$files" ] && abort "No testpoints found in $dir"
fi

first="$(printf "%s" "$files" | head -1)"

# if output is to a terminal, and gnuplot exists, pipe to gnuplot
plotcmd="$(command -v gnuplot)"
if [ -n "$plotcmd" ] && [ -t 1 ] ; then
	plotscript="set datafile separator ',' ; plot '-' using 1:3 with linespoints title column"
	plotcmd="$plotcmd -p -e"
else
	plotscript=cat
	plotcmd=
fi

{
head -1 "$first"
sed -s -n "$((id+2))p" $files
} | $plotcmd "$plotscript"
