#!/bin/bash
# SSS by Eugenio Rustico (rustico@dmi.unict.it)
# usage example: ./sss d_dem -C 2
if [ "$#" = "0" ]
then
	echo "SSS: look for the specified patterns in current directory."
	echo "Synopsys:"
	echo "    sss [-e] pattern [grep options]"
	echo 'Default extensions: *.cc *.h *.cuh *.cu'
	echo "Examples:"
	echo "  $ sss FIXME"
	echo "  $ sss \"#include <stdio>\" -i"
	echo "  $ sss -e \"^/// R\" -e -C 1"
	exit 1
fi
ls *.cc *.h *.cuh *.cu 2> /dev/null | while read filename
do
	grep -n --color=always "$@" "$filename" /dev/null
done

