#define BIFLUIDPOISEUILLE_BOUNDARY SA_BOUNDARY
#define BIFLUIDPOISEUILLE_FLAGS ENABLE_MULTIFLUID | ENABLE_DTADAPT | ENABLE_DENSITY_SUM

#include "BiFluidPoiseuilleSA.h"
#include "BiFluidPoiseuille.inc"
